// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/top": {
    params: {};
  };
  "/create-question": {
    params: {};
  };
  "/question/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/top" | "/create-question" | "/question/:id" | "/profile";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/";
  };
  "layouts/auth-guard.tsx": {
    id: "layouts/auth-guard";
    page: "/top" | "/create-question" | "/question/:id" | "/profile";
  };
  "routes/top.tsx": {
    id: "routes/top";
    page: "/top";
  };
  "routes/createQuestion.tsx": {
    id: "routes/createQuestion";
    page: "/create-question";
  };
  "routes/question.tsx": {
    id: "routes/question";
    page: "/question/:id";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "layouts/auth-guard": typeof import("./app/layouts/auth-guard.tsx");
  "routes/top": typeof import("./app/routes/top.tsx");
  "routes/createQuestion": typeof import("./app/routes/createQuestion.tsx");
  "routes/question": typeof import("./app/routes/question.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
};